SELECT *
FROM MOVIE
WHERE STUDIONAME LIKE 'Disney' AND YEAR LIKE 1990 

SELECT *
FROM MOVIE
WHERE STUDIONAME NOT LIKE 'Disney' AND YEAR NOT LIKE 1990 

SELECT *
FROM MOVIE
WHERE STUDIONAME NOT LIKE 'Disney' AND YEAR NOT LIKE 1990
ORDER BY LENGTH

SELECT *
FROM MOVIE
WHERE STUDIONAME NOT LIKE 'Disney' AND YEAR NOT LIKE 1990
ORDER BY STUDIONAME ASC

SELECT *
FROM MOVIE
WHERE STUDIONAME NOT LIKE 'Disney' AND YEAR NOT LIKE 1990
ORDER BY LENGTH, TITLE ASC

