SELECT B.TITLE, B.YEAR, B.LENGTH
FROM  (SELECT YEAR FROM MOVIE WHERE YEAR<2000)as A
JOIN (SELECT TITLE, YEAR, LENGTH FROM MOVIE WHERE LENGTH>120 OR LENGTH IS NULL) as B ON (A.YEAR=B.YEAR)

SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND BIRTHDATE>1948
ORDER BY NAME DESC

SELECT A.STUDIONAME, COUNT(DISTINCT STARNAME)
FROM (SELECT STUDIONAME, TITLE FROM MOVIE) as A, STARSIN 
WHERE A.TITLE=STARSIN.MOVIETITLE
GROUP BY A.STUDIONAME

SELECT DISTINCT STARNAME, COUNT(MOVIETITLE)as MOVIES
FROM STARSIN
GROUP BY STARNAME

SELECT A.STUDIONAME, MOVIE.TITLE, A.LAST
FROM (SELECT DISTINCT STUDIONAME, MAX(MOVIE.YEAR)as LAST FROM MOVIE GROUP BY STUDIONAME)as A, MOVIE
WHERE MOVIE.STUDIONAME=A.STUDIONAME AND A.LAST=MOVIE.YEAR

SELECT MOVIESTAR.NAME
FROM (SELECT MAX(MOVIESTAR.BIRTHDATE) as LAST FROM MOVIESTAR WHERE GENDER='M')as A, MOVIESTAR
WHERE MOVIESTAR.BIRTHDATE=A.LAST

SELECT AB.STUDIONAME, AB.STARNAME, AB.MOVIES
FROM (SELECT MAX(AB.MOVIES) as MAX FROM (SELECT DISTINCT A.STUDIONAME,B.STARNAME, COUNT(DISTINCT A.TITLE)as MOVIES FROM (SELECT TITLE, MOVIE.STUDIONAME FROM MOVIE)as A, (SELECT STARSIN.MOVIETITLE, STARSIN.STARNAME FROM STARSIN) as B WHERE A.TITLE=B.MOVIETITLE GROUP BY B.STARNAME, A.STUDIONAME) as AB) as C
JOIN (SELECT DISTINCT A.STUDIONAME,B.STARNAME, COUNT(DISTINCT A.TITLE)as MOVIES FROM (SELECT TITLE, MOVIE.STUDIONAME FROM MOVIE)as A, (SELECT STARSIN.MOVIETITLE, STARSIN.STARNAME FROM STARSIN) as B WHERE A.TITLE=B.MOVIETITLE GROUP BY B.STARNAME, A.STUDIONAME) as AB ON(AB.MOVIES=C.MAX)

SELECT STARSIN.MOVIETITLE, STARSIN.MOVIEYEAR, COUNT( STARSIN.STARNAME)as num_actor
FROM  STARSIN
GROUP BY STARSIN.MOVIETITLE, STARSIN.MOVIEYEAR
HAVING COUNT(STARSIN.STARNAME)>2