SELECT C.NAME, AB.TITLE
FROM (SELECT B.NAME, B.CERT# FROM (SELECT MOVIE.PRODUCERC# FROM MOVIE WHERE MOVIE.TITLE='Star Wars') as A JOIN MOVIEEXEC B ON(B.CERT#=A.PRODUCERC#)) as C
JOIN MOVIE AB ON (AB.PRODUCERC#=C.CERT#)

SELECT DISTINCT C.NAME
FROM (SELECT A.MOVIETITLE, B.PRODUCERC# FROM (SELECT STARSIN.MOVIETITLE FROM STARSIN WHERE STARSIN.STARNAME='Harrison Ford') as A JOIN (SELECT MOVIE.PRODUCERC#, MOVIE.TITLE FROM MOVIE) as B ON (B.TITLE=A.MOVIETITLE))as AB
JOIN (SELECT MOVIEEXEC.CERT#, MOVIEEXEC.NAME FROM MOVIEEXEC) as C ON (C.CERT#=AB.PRODUCERC#)

SELECT DISTINCT B.NAME, STARSIN.STARNAME
FROM (SELECT A.NAME, MOVIE.TITLE FROM (SELECT STUDIO.NAME FROM STUDIO)as A JOIN MOVIE ON (MOVIE.STUDIONAME=A.NAME)) as B, STARSIN
WHERE B.TITLE=STARSIN.MOVIETITLE
ORDER BY B.NAME

SELECT DISTINCT STARSIN.STARNAME
FROM (SELECT A.TITLE FROM (SELECT MOVIEEXEC.CERT# FROM MOVIEEXEC, (SELECT MAX(MOVIEEXEC.NETWORTH) as NET FROM MOVIEEXEC) as B WHERE MOVIEEXEC.NETWORTH=B.NET) as C JOIN MOVIE A ON(C.CERT#=A.PRODUCERC#))as AB
JOIN STARSIN ON (AB.TITLE=STARSIN.MOVIETITLE)

SELECT DISTINCT MOVIESTAR.NAME
FROM MOVIESTAR
EXCEPT
SELECT DISTINCT STARSIN.STARNAME
FROM STARSIN

