SELECT ADDRESS
FROM STUDIO
WHERE NAME='DISNEY'

SELECT BIRTHDATE 
FROM MOVIESTAR
WHERE NAME LIKE 'JACK NICHOLSON'

SELECT STARNAME
FROM STARSIN
WHERE MOVIETITLE LIKE '%KNIGHT%' OR MOVIEYEAR LIKE 1980 

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000
 
SELECT NAME
FROM MOVIESTAR
WHERE GENDER LIKE 'M' OR ADDRESS LIKE 'Prefect Rd.'