SELECT A.NAME
FROM (SELECT NAME FROM MOVIESTAR WHERE GENDER='F') A, (SELECT NAME FROM MOVIEEXEC WHERE NETWORTH>10000000) B
WHERE A.NAME=B.NAME

SELECT DISTINCT MOVIESTAR.NAME
FROM MOVIESTAR, MOVIEEXEC
WHERE MOVIESTAR.NAME!=MOVIEEXEC.NAME

SELECT MOVIE.TITLE
FROM (SELECT LENGTH FROM MOVIE WHERE TITLE='Star Wars') A, MOVIE
WHERE MOVIE.LENGTH>A.LENGTH

SELECT MOVIE.TITLE, ALFA.NAME
FROM (SELECT CERT#, NAME FROM MOVIEEXEC, (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Merv Griffin') A WHERE MOVIEEXEC.NETWORTH>A.NETWORTH) ALFA, MOVIE
WHERE ALFA.CERT#=MOVIE.PRODUCERC#