SELECT *
FROM SHIPS
JOIN (SELECT * FROM CLASSES)as B ON (SHIPS.CLASS=B.CLASS)

SELECT *
FROM SHIPS
FULL JOIN (SELECT * FROM CLASSES)as B ON (SHIPS.CLASS=B.CLASS)

SELECT DISTINCT C.COUNTRY, C.NAME
FROM (SELECT DISTINCT A.COUNTRY, B.NAME FROM (SELECT CLASSES.COUNTRY, CLASSES.CLASS FROM CLASSES)as A JOIN SHIPS as B ON (A.CLASS=B.CLASS))as C
EXCEPT
SELECT DISTINCT C.COUNTRY, C.NAME
FROM (SELECT DISTINCT A.COUNTRY, B.NAME FROM (SELECT CLASSES.COUNTRY, CLASSES.CLASS FROM CLASSES)as A JOIN SHIPS as B ON (A.CLASS=B.CLASS))as C
JOIN OUTCOMES as AB ON (C.NAME=AB.SHIP)

SELECT DISTINCT B.NAME as 'Ship Name' 
FROM (SELECT CLASSES.CLASS FROM CLASSES WHERE NUMGUNS>=7) as A 
JOIN SHIPS as B ON (A.CLASS=B.CLASS) 
WHERE B.LAUNCHED=1916

SELECT A.SHIP ,A.BATTLE, BATTLES.DATE
FROM (SELECT * FROM OUTCOMES WHERE RESULT='sunk')as A,BATTLES
WHERE BATTLES.NAME=A.BATTLE
ORDER BY A.BATTLE

SELECT A.CLASS, B.DISPLACEMENT, A.LAUNCHED
FROM (SELECT SHIPS.CLASS, SHIPS.LAUNCHED FROM SHIPS WHERE SHIPS.CLASS=SHIPS.NAME) as A
JOIN CLASSES as B ON (A.CLASS=B.CLASS)

SELECT *
FROM (SELECT CLASS FROM CLASSES EXCEPT SELECT CLASS FROM SHIPS) as A, CLASSES
WHERE CLASSES.CLASS=A.CLASS

SELECT B.NAME,C.DISPLACEMENT,C.NUMGUNS, A.RESULT
FROM (SELECT OUTCOMES.SHIP, OUTCOMES.RESULT FROM OUTCOMES WHERE BATTLE='North Atlantic') as A
JOIN SHIPS as B ON(B.NAME=A.SHIP)
JOIN CLASSES as C ON (C.CLASS=B.CLASS)

