SELECT NAME
FROM CLASSES, SHIPS
WHERE DISPLACEMENT>50000 AND CLASSES.CLASS=SHIPS.CLASS

SELECT DISTINCT SHIPS.NAME, DISPLACEMENT, NUMGUNS
FROM CLASSES, OUTCOMES,SHIPS
WHERE  BATTLE='Guadalcanal' AND OUTCOMES.SHIP=SHIPS.NAME AND SHIPS.CLASS=CLASSES.CLASS

SELECT DISTINCT COUNTRY
FROM CLASSES
GROUP BY COUNTRY
HAVING COUNT(DISTINCT TYPE)>1

SELECT SHIP 
FROM OUTCOMES 
GROUP BY SHIP
HAVING COUNT(DISTINCT RESULT)>1